spring:
  application:
    name: mscartoes
server:
  port: 0 # inicia em um porta ramdomica
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
