spring:
  application:
    name: mscartoes
  rabbitmq:
    #host: localhost
    host: ${RABBITMQ_SERVER}
    port: 5672
    username: guest
    password: guest

server:
  port: 0 # inicia em um porta ramdomica

eureka:
  client:
    service-url:
      defaultZone: http://cursoms-eureka-user:cursoms-eureka-user@${EUREKA_SERVER}:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

mq:
  queue:
    emissao-cartoes: emissao-cartoes

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: ./logs/log-file.log
